@startuml system_manager
skinparam arrowcolor red
skinparam stateBackgroundColor yellow  

[*] --> SET_RTC_STATE
SET_RTC_STATE: Display a text for setting time and date for the device

DISPLAY_BLINKING_SET_TIME: Display set time, set date and blink the set time part

DISPLAY_BLINKING_SET_TIME_HOUR: Display time and blink the hour part
DISPLAY_BLINKING_SET_TIME_MINUTE: Display time and blink the minutes part
DISPLAY_BLINKING_SET_TIME_SECOND: Display time and blink the seconds part

DISPLAY_BLINKING_SET_TIME_HOUR_PLUS_1: Display time and blink the hour part plus 1
DISPLAY_BLINKING_SET_TIME_MINUTE_PLUS_1: Display time and blink the minutes part plus 1
DISPLAY_BLINKING_SET_TIME_SECOND_PLUS_1: Display time and blink the seconds part plus 1


DISPLAY_BLINKING_SET_DATE: Display set time, set date and blink the set date part

DISPLAY_BLINKING_SET_DATE_DATE: Display time and blink the date part
DISPLAY_BLINKING_SET_DATE_MONTH: Display time and blink the month part
DISPLAY_BLINKING_SET_DATE_YEAR: Display time and blink the year part

DISPLAY_BLINKING_SET_DATE_DATE_PLUS_1: Display time and blink the date part plus 1
DISPLAY_BLINKING_SET_DATE_MONTH_PLUS_1: Display time and blink the month part plus 1
DISPLAY_BLINKING_SET_DATE_YEAR_PLUS_1: Display time and blink the year part plus 1

SET_RTC_STATE --> DISPLAY_BLINKING_SET_TIME: Double click
DISPLAY_BLINKING_SET_TIME --> DISPLAY_BLINKING_SET_DATE: Double click
DISPLAY_BLINKING_SET_DATE --> DISPLAY_BLINKING_SET_TIME: Double click
DISPLAY_BLINKING_SET_TIME --> SET_RTC_STATE: Hold button >= 3 seconds
DISPLAY_BLINKING_SET_DATE --> SET_RTC_STATE: Hold button >= 3 seconds

DISPLAY_BLINKING_SET_TIME --> DISPLAY_BLINKING_SET_TIME_HOUR: Single click

DISPLAY_BLINKING_SET_TIME_HOUR --> DISPLAY_BLINKING_SET_TIME_HOUR_PLUS_1: Single click
DISPLAY_BLINKING_SET_TIME_HOUR_PLUS_1 --> DISPLAY_BLINKING_SET_TIME_HOUR: Increase hour value by 1
DISPLAY_BLINKING_SET_TIME_HOUR --> DISPLAY_BLINKING_SET_TIME_MINUTE: Double click
DISPLAY_BLINKING_SET_TIME_HOUR --> DISPLAY_BLINKING_SET_TIME: Hold button >= 3 seconds

DISPLAY_BLINKING_SET_TIME_MINUTE --> DISPLAY_BLINKING_SET_TIME_MINUTE_PLUS_1: Single click
DISPLAY_BLINKING_SET_TIME_MINUTE_PLUS_1 --> DISPLAY_BLINKING_SET_TIME_MINUTE: Increase minute value by 1
DISPLAY_BLINKING_SET_TIME_MINUTE --> DISPLAY_BLINKING_SET_TIME_SECOND: Double click
DISPLAY_BLINKING_SET_TIME_MINUTE --> DISPLAY_BLINKING_SET_TIME: Hold button >= 3 seconds

DISPLAY_BLINKING_SET_TIME_SECOND --> DISPLAY_BLINKING_SET_TIME_SECOND_PLUS_1: Single click
DISPLAY_BLINKING_SET_TIME_SECOND_PLUS_1 --> DISPLAY_BLINKING_SET_TIME_SECOND: Increase second value by 1
DISPLAY_BLINKING_SET_TIME_SECOND --> DISPLAY_BLINKING_SET_TIME_HOUR: Double click
DISPLAY_BLINKING_SET_TIME_SECOND --> DISPLAY_BLINKING_SET_TIME: Hold button >= 3 seconds


DISPLAY_BLINKING_SET_DATE --> DISPLAY_BLINKING_SET_DATE_DATE: Single click

DISPLAY_BLINKING_SET_DATE_DATE --> DISPLAY_BLINKING_SET_DATE_DATE_PLUS_1: Single click
DISPLAY_BLINKING_SET_DATE_DATE_PLUS_1 --> DISPLAY_BLINKING_SET_DATE_DATE: Increase date value by 1
DISPLAY_BLINKING_SET_DATE_DATE --> DISPLAY_BLINKING_SET_DATE_MONTH: Double click
DISPLAY_BLINKING_SET_DATE_DATE --> DISPLAY_BLINKING_SET_DATE: Hold button >= 3 seconds

DISPLAY_BLINKING_SET_DATE_MONTH --> DISPLAY_BLINKING_SET_DATE_MONTH_PLUS_1: Single click
DISPLAY_BLINKING_SET_DATE_MONTH_PLUS_1 --> DISPLAY_BLINKING_SET_DATE_MONTH: Increase month value by 1
DISPLAY_BLINKING_SET_DATE_MONTH --> DISPLAY_BLINKING_SET_DATE_YEAR: Double click
DISPLAY_BLINKING_SET_DATE_MONTH --> DISPLAY_BLINKING_SET_DATE: Hold button >= 3 seconds

DISPLAY_BLINKING_SET_DATE_YEAR --> DISPLAY_BLINKING_SET_DATE_YEAR_PLUS_1: Single click
DISPLAY_BLINKING_SET_DATE_YEAR_PLUS_1 --> DISPLAY_BLINKING_SET_DATE_YEAR: Increase date value by 1
DISPLAY_BLINKING_SET_DATE_YEAR --> DISPLAY_BLINKING_SET_DATE_DATE: Double click
DISPLAY_BLINKING_SET_DATE_YEAR --> DISPLAY_BLINKING_SET_DATE: Hold button >= 3 seconds

@enduml